# 简化的Pre-commit hooks配置
# 安装: pip install pre-commit && pre-commit install
# 运行: pre-commit run --all-files

repos:
  # 基础检查
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        description: 移除行尾空白字符
      - id: end-of-file-fixer
        description: 确保文件以换行符结尾
      - id: check-merge-conflict
        description: 检查合并冲突标记
      - id: check-added-large-files
        description: 防止添加大文件
        args: ['--maxkb=1000']

  # Python代码格式化
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        description: Black代码格式化
        language_version: python3
        args: [--line-length=127]

  # 导入排序
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        description: isort导入排序
        args: [--profile=black, --line-length=127]

  # 代码检查
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        description: Flake8代码检查
        args: [--max-line-length=127, --max-complexity=10]

# 全局配置
default_stages: [commit]
fail_fast: true  # 快速失败，提高效率