name: Simplified CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']  # 支持Python 3.9+

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8 black isort
    
    - name: Code quality checks
      run: |
        black --check --diff . || true
        isort --check-only --diff . || true
        flake8 . --count --max-complexity=15 --max-line-length=127 --statistics --ignore=E203,W503,E501
      continue-on-error: true
    
    - name: Run tests
      run: |
        pytest tests/ --cov=dialogue_manager --cov-report=term-missing --cov-fail-under=60
      env:
        SILICONFLOW_API_KEY: ${{ secrets.SILICONFLOW_API_KEY }}
      continue-on-error: false
    
    - name: Basic security check
      run: |
        pip install bandit
        bandit -r dialogue_manager/ -ll
      continue-on-error: true